# Generated by Django 5.1 on 2024-11-23 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('lastName', models.CharField(max_length=250, verbose_name='Apellido')),
                ('birthDate', models.DateField(verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('becado', models.BooleanField(verbose_name='Estudiante becado')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('numberOfCredits', models.IntegerField(verbose_name='Número de créditos')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=250, verbose_name='Apellido')),
                ('state', models.CharField(max_length=250, verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationDate', models.DateField(verbose_name='Fecha de registro')),
                ('site', models.CharField(choices=[('SA', 'Sede A'), ('SB', 'Sede B')], default='SA', max_length=100, verbose_name='Tipo de sede')),
                ('journey', models.CharField(choices=[('DI', 'Diurna'), ('NO', 'Nocturna')], default='DI', max_length=100, verbose_name='Tipo de jornada')),
                ('careerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.career', verbose_name='Carrera')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student', verbose_name='Estudiante')),
                ('subjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject', verbose_name='Materia')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='teacherId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher', verbose_name='Profesor'),
        ),
    ]
